export const THEME_PRESETS = [
  {
    name: "Midnight",
    opacity: 50,
    panelColor: "#0c1222",
    aiColor: "#e2e8f0",
    userColor: "#60a5fa",
  },
  {
    name: "AMOLED",
    opacity: 90,
    panelColor: "#000000",
    aiColor: "#1e293b",
    userColor: "#4ade80",
  },
  {
    name: "Slime",
    opacity: 60,
    panelColor: "#0a1f14",
    aiColor: "#a7f3d0",
    userColor: "#6ee7b7",
  },
  {
    name: "Sakura",
    opacity: 55,
    panelColor: "#1c0d1a",
    aiColor: "#f9e8ef",
    userColor: "#f9a8d4",
  },
  {
    name: "Cherry",
    opacity: 60,
    panelColor: "#1f0a0c",
    aiColor: "#fce4ec",
    userColor: "#fb7185",
  },
  {
    name: "Ocean",
    opacity: 55,
    panelColor: "#081c2e",
    aiColor: "#cffafe",
    userColor: "#38bdf8",
  },
  {
    name: "Violet",
    opacity: 55,
    panelColor: "#140c26",
    aiColor: "#e9d5ff",
    userColor: "#a78bfa",
  },
  {
    name: "Sunset",
    opacity: 55,
    panelColor: "#1f0f06",
    aiColor: "#ffedd5",
    userColor: "#fb923c",
  },
  {
    name: "Cyber",
    opacity: 55,
    panelColor: "#0c1222",
    aiColor: "#a5f3fc",
    userColor: "#c084fc",
  },
];